version: '3.3'

services:

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: r00t

      #  adminer:
      #    image: adminer
      #    restart: always
      #    ports:
      #      - 8080:8080
      #

  oracledb:
    image: oracle/database:12.2.0.1-ee
    ports:
    - 1521:1521
    - 5500:5500
    environment:
    - ORACLE_SID:xe
    - ORACLE_PDB=duwamishpdb
    - ORACLE_PWD=Duwamish9
    - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
    - /data/oracle:/opt/oracle/oradata
    - ./db:/docker-entrypoint-initdb.d/setup
